# Site settings
title: Edison & Jenny
email:
description: "Yo y mi Casa serviremos a Jehova"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key: https://www.google.com/maps/embed/v1/view?key=AIzaSyA-p_kHQpNkm_9yCBdAE8yDQwFJnECSXNI&center=25.486093, -100.184973 &zoom=15 &maptype=satellite

# Build settings
markdown: kramdown
