# Site settings
title: EDISON&JENNY
email: vazquezedison@gmail.com
description: "hello"
baseurl: "/boda/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# User setting
owner: Edison&Jenny
email: vazquezedison@gmail.com
address:
  - line: Casrretera Nacional Km. 257, San Roberto S/N
  - line: "Santiago, NL 67300"
  # Feel free to add more lines here 
telephone: 55-545-707-89
copyright: edison

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown
