# Site settings
title: EDISON&JENNY
email: your-email@domain.com
description: "hello"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# User setting
owner: Edison
email: name@example.com
facebook_username: example
twitter_username: example
github_username: example
address:
  - line: 3481 Melrose Hill St
  - line: "Los Angeles, CA 90029"
  # Feel free to add more lines here 
telephone: (123) 456-7890
copyright: Your Site

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown
